### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by ryumada** [REPfit-Retail-Price-Fit/backend-main#2]
Create API documentation using Github Repository Wiki.

I've created an API Documentation Example, right at this link:
https://github.com/ryumada/docs-restapi

The attributes for API documentation are in this link below:
https://story-api.dicoding.dev/v1/#/?id=dicoding-story

**Comment by ryumada** [comment]
I created the documentation for the first 3 features. Here is the [commit](https://github.com/REPfit-Retail-Price-Fit/backend-main/commit/de4a6fad86b5515fecf8ddb8d47e4058ae9980c0).

**Comment by ryumada** [comment]
@akhfzz please check the documentation I made. Please consider to check it if there is something wrong. we can discussed it together.

And for @reyhanalfaritsi, I have made the basic API documentation, please check it also.

Thanks

**Comment by akhfzz** [comment]
@ryumada i have read, and response from API which i made, i can't writting now. bcz firstly i want test each of unit untill derive green marks. wait...
