### ISSUE TITLE
Penggunaan link buat forget password

### ISSUE THREAD

**Issue by ryumada** [REPfit-Retail-Price-Fit/backend-main#7]
https://github.com/REPfit-Retail-Price-Fit/backend-main/blob/909c3a77b276970bbd4409f369f4fba8b922ccaa/docs/login/recover/%5BPOST%5D%20Forget%20password.md?plain=1#L5

menurut saya agak aneh dah sal kalo kamu namainnya pake `/api/sys-reset-psw/`, kenapa harus begini sal? @akhfzz 

karena biasanya kalo saya liat2 pada make `/api/recovery/` buat recover akun.

**Comment by akhfzz** [comment]
@ryumada aku lupa adanya firewall terus ip private dan public hehe. Td nya aku mikir penamaan yang unik ttg API tuh mas biar user lain ga asal request ke routing backend kita, hehe lupa kan ada konsep publik dan private ip ga kepikiran kesitu :D

**Comment by ryumada** [comment]
oke oke gpp, saya coba revisi lagi ya, inget lain kali kalo mau ngubah bikin branch baru dulu trus bikin [pull request](https://github.com/REPfit-Retail-Price-Fit/backend-main/pulls) kalo mau masukin perubahan. Tujuannya biar direview dulu sal.
